// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace deliveryApp.Server.CompiledModels
{
    public partial class DeliveryAppDbContextModel
    {
        partial void Initialize()
        {
            var cuisineType = CuisineTypeEntityType.Create(this);
            var menuItem = MenuItemEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderItem = OrderItemEntityType.Create(this);
            var restaurant = RestaurantEntityType.Create(this);
            var restaurantHour = RestaurantHourEntityType.Create(this);
            var role = RoleEntityType.Create(this);
            var user = UserEntityType.Create(this);

            MenuItemEntityType.CreateForeignKey1(menuItem, restaurant);
            OrderEntityType.CreateForeignKey1(order, user);
            OrderEntityType.CreateForeignKey2(order, user);
            OrderEntityType.CreateForeignKey3(order, restaurant);
            OrderItemEntityType.CreateForeignKey1(orderItem, menuItem);
            OrderItemEntityType.CreateForeignKey2(orderItem, order);
            RestaurantEntityType.CreateForeignKey1(restaurant, cuisineType);
            RestaurantHourEntityType.CreateForeignKey1(restaurantHour, restaurant);
            UserEntityType.CreateForeignKey1(user, role);

            CuisineTypeEntityType.CreateAnnotations(cuisineType);
            MenuItemEntityType.CreateAnnotations(menuItem);
            OrderEntityType.CreateAnnotations(order);
            OrderItemEntityType.CreateAnnotations(orderItem);
            RestaurantEntityType.CreateAnnotations(restaurant);
            RestaurantHourEntityType.CreateAnnotations(restaurantHour);
            RoleEntityType.CreateAnnotations(role);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "8.0.27");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var cuisineType = FindEntityType("deliveryApp.Server.Models.CuisineType")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            cuisineType.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var deliveryAppServerModelsCuisineTypeTableBase = new TableBase("deliveryApp.Server.Models.CuisineType", null, relationalModel);
            var cuisineTypeIdColumnBase = new ColumnBase<ColumnMappingBase>("CuisineTypeId", "int", deliveryAppServerModelsCuisineTypeTableBase);
            deliveryAppServerModelsCuisineTypeTableBase.Columns.Add("CuisineTypeId", cuisineTypeIdColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "nvarchar(max)", deliveryAppServerModelsCuisineTypeTableBase);
            deliveryAppServerModelsCuisineTypeTableBase.Columns.Add("Name", nameColumnBase);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.CuisineType", deliveryAppServerModelsCuisineTypeTableBase);
            var deliveryAppServerModelsCuisineTypeMappingBase = new TableMappingBase<ColumnMappingBase>(cuisineType, deliveryAppServerModelsCuisineTypeTableBase, true);
            deliveryAppServerModelsCuisineTypeTableBase.AddTypeMapping(deliveryAppServerModelsCuisineTypeMappingBase, false);
            defaultTableMappings.Add(deliveryAppServerModelsCuisineTypeMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cuisineTypeIdColumnBase, cuisineType.FindProperty("CuisineTypeId")!, deliveryAppServerModelsCuisineTypeMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, cuisineType.FindProperty("Name")!, deliveryAppServerModelsCuisineTypeMappingBase);

            var tableMappings = new List<TableMapping>();
            cuisineType.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var cuisineTypesTable = new Table("CuisineTypes", null, relationalModel);
            var cuisineTypeIdColumn = new Column("CuisineTypeId", "int", cuisineTypesTable);
            cuisineTypesTable.Columns.Add("CuisineTypeId", cuisineTypeIdColumn);
            var nameColumn = new Column("Name", "nvarchar(max)", cuisineTypesTable);
            cuisineTypesTable.Columns.Add("Name", nameColumn);
            var pK_CuisineTypes = new UniqueConstraint("PK_CuisineTypes", cuisineTypesTable, new[] { cuisineTypeIdColumn });
            cuisineTypesTable.PrimaryKey = pK_CuisineTypes;
            var pK_CuisineTypesUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.CuisineType",
                new[] { "CuisineTypeId" });
            pK_CuisineTypes.MappedKeys.Add(pK_CuisineTypesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_CuisineTypesUc).Add(pK_CuisineTypes);
            cuisineTypesTable.UniqueConstraints.Add("PK_CuisineTypes", pK_CuisineTypes);
            relationalModel.Tables.Add(("CuisineTypes", null), cuisineTypesTable);
            var cuisineTypesTableMapping = new TableMapping(cuisineType, cuisineTypesTable, true);
            cuisineTypesTable.AddTypeMapping(cuisineTypesTableMapping, false);
            tableMappings.Add(cuisineTypesTableMapping);
            RelationalModel.CreateColumnMapping(cuisineTypeIdColumn, cuisineType.FindProperty("CuisineTypeId")!, cuisineTypesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, cuisineType.FindProperty("Name")!, cuisineTypesTableMapping);

            var menuItem = FindEntityType("deliveryApp.Server.Models.MenuItem")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            menuItem.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var deliveryAppServerModelsMenuItemTableBase = new TableBase("deliveryApp.Server.Models.MenuItem", null, relationalModel);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "nvarchar(max)", deliveryAppServerModelsMenuItemTableBase);
            deliveryAppServerModelsMenuItemTableBase.Columns.Add("Description", descriptionColumnBase);
            var imageUrlColumnBase = new ColumnBase<ColumnMappingBase>("ImageUrl", "nvarchar(max)", deliveryAppServerModelsMenuItemTableBase);
            deliveryAppServerModelsMenuItemTableBase.Columns.Add("ImageUrl", imageUrlColumnBase);
            var menuItemIdColumnBase = new ColumnBase<ColumnMappingBase>("MenuItemId", "int", deliveryAppServerModelsMenuItemTableBase);
            deliveryAppServerModelsMenuItemTableBase.Columns.Add("MenuItemId", menuItemIdColumnBase);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "nvarchar(max)", deliveryAppServerModelsMenuItemTableBase);
            deliveryAppServerModelsMenuItemTableBase.Columns.Add("Name", nameColumnBase0);
            var priceColumnBase = new ColumnBase<ColumnMappingBase>("Price", "decimal(18,2)", deliveryAppServerModelsMenuItemTableBase);
            deliveryAppServerModelsMenuItemTableBase.Columns.Add("Price", priceColumnBase);
            var restaurantIdColumnBase = new ColumnBase<ColumnMappingBase>("RestaurantId", "int", deliveryAppServerModelsMenuItemTableBase);
            deliveryAppServerModelsMenuItemTableBase.Columns.Add("RestaurantId", restaurantIdColumnBase);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.MenuItem", deliveryAppServerModelsMenuItemTableBase);
            var deliveryAppServerModelsMenuItemMappingBase = new TableMappingBase<ColumnMappingBase>(menuItem, deliveryAppServerModelsMenuItemTableBase, true);
            deliveryAppServerModelsMenuItemTableBase.AddTypeMapping(deliveryAppServerModelsMenuItemMappingBase, false);
            defaultTableMappings0.Add(deliveryAppServerModelsMenuItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)menuItemIdColumnBase, menuItem.FindProperty("MenuItemId")!, deliveryAppServerModelsMenuItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, menuItem.FindProperty("Description")!, deliveryAppServerModelsMenuItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)imageUrlColumnBase, menuItem.FindProperty("ImageUrl")!, deliveryAppServerModelsMenuItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, menuItem.FindProperty("Name")!, deliveryAppServerModelsMenuItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)priceColumnBase, menuItem.FindProperty("Price")!, deliveryAppServerModelsMenuItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)restaurantIdColumnBase, menuItem.FindProperty("RestaurantId")!, deliveryAppServerModelsMenuItemMappingBase);

            var tableMappings0 = new List<TableMapping>();
            menuItem.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var menuItemsTable = new Table("MenuItems", null, relationalModel);
            var menuItemIdColumn = new Column("MenuItemId", "int", menuItemsTable);
            menuItemsTable.Columns.Add("MenuItemId", menuItemIdColumn);
            var descriptionColumn = new Column("Description", "nvarchar(max)", menuItemsTable);
            menuItemsTable.Columns.Add("Description", descriptionColumn);
            var imageUrlColumn = new Column("ImageUrl", "nvarchar(max)", menuItemsTable);
            menuItemsTable.Columns.Add("ImageUrl", imageUrlColumn);
            var nameColumn0 = new Column("Name", "nvarchar(max)", menuItemsTable);
            menuItemsTable.Columns.Add("Name", nameColumn0);
            var priceColumn = new Column("Price", "decimal(18,2)", menuItemsTable);
            menuItemsTable.Columns.Add("Price", priceColumn);
            var restaurantIdColumn = new Column("RestaurantId", "int", menuItemsTable);
            menuItemsTable.Columns.Add("RestaurantId", restaurantIdColumn);
            var pK_MenuItems = new UniqueConstraint("PK_MenuItems", menuItemsTable, new[] { menuItemIdColumn });
            menuItemsTable.PrimaryKey = pK_MenuItems;
            var pK_MenuItemsUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.MenuItem",
                new[] { "MenuItemId" });
            pK_MenuItems.MappedKeys.Add(pK_MenuItemsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_MenuItemsUc).Add(pK_MenuItems);
            menuItemsTable.UniqueConstraints.Add("PK_MenuItems", pK_MenuItems);
            var iX_MenuItems_RestaurantId = new TableIndex(
            "IX_MenuItems_RestaurantId", menuItemsTable, new[] { restaurantIdColumn }, false);
            var iX_MenuItems_RestaurantIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.MenuItem",
                new[] { "RestaurantId" });
            iX_MenuItems_RestaurantId.MappedIndexes.Add(iX_MenuItems_RestaurantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_MenuItems_RestaurantIdIx).Add(iX_MenuItems_RestaurantId);
            menuItemsTable.Indexes.Add("IX_MenuItems_RestaurantId", iX_MenuItems_RestaurantId);
            relationalModel.Tables.Add(("MenuItems", null), menuItemsTable);
            var menuItemsTableMapping = new TableMapping(menuItem, menuItemsTable, true);
            menuItemsTable.AddTypeMapping(menuItemsTableMapping, false);
            tableMappings0.Add(menuItemsTableMapping);
            RelationalModel.CreateColumnMapping(menuItemIdColumn, menuItem.FindProperty("MenuItemId")!, menuItemsTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, menuItem.FindProperty("Description")!, menuItemsTableMapping);
            RelationalModel.CreateColumnMapping(imageUrlColumn, menuItem.FindProperty("ImageUrl")!, menuItemsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, menuItem.FindProperty("Name")!, menuItemsTableMapping);
            RelationalModel.CreateColumnMapping(priceColumn, menuItem.FindProperty("Price")!, menuItemsTableMapping);
            RelationalModel.CreateColumnMapping(restaurantIdColumn, menuItem.FindProperty("RestaurantId")!, menuItemsTableMapping);

            var order = FindEntityType("deliveryApp.Server.Models.Order")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            order.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var deliveryAppServerModelsOrderTableBase = new TableBase("deliveryApp.Server.Models.Order", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "datetime2", deliveryAppServerModelsOrderTableBase);
            deliveryAppServerModelsOrderTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var customerIdColumnBase = new ColumnBase<ColumnMappingBase>("CustomerId", "int", deliveryAppServerModelsOrderTableBase);
            deliveryAppServerModelsOrderTableBase.Columns.Add("CustomerId", customerIdColumnBase);
            var driverIdColumnBase = new ColumnBase<ColumnMappingBase>("DriverId", "int", deliveryAppServerModelsOrderTableBase)
            {
                IsNullable = true
            };
            deliveryAppServerModelsOrderTableBase.Columns.Add("DriverId", driverIdColumnBase);
            var orderIdColumnBase = new ColumnBase<ColumnMappingBase>("OrderId", "int", deliveryAppServerModelsOrderTableBase);
            deliveryAppServerModelsOrderTableBase.Columns.Add("OrderId", orderIdColumnBase);
            var restaurantIdColumnBase0 = new ColumnBase<ColumnMappingBase>("RestaurantId", "int", deliveryAppServerModelsOrderTableBase);
            deliveryAppServerModelsOrderTableBase.Columns.Add("RestaurantId", restaurantIdColumnBase0);
            var statusColumnBase = new ColumnBase<ColumnMappingBase>("Status", "nvarchar(max)", deliveryAppServerModelsOrderTableBase);
            deliveryAppServerModelsOrderTableBase.Columns.Add("Status", statusColumnBase);
            var totalPriceColumnBase = new ColumnBase<ColumnMappingBase>("TotalPrice", "decimal(18,2)", deliveryAppServerModelsOrderTableBase);
            deliveryAppServerModelsOrderTableBase.Columns.Add("TotalPrice", totalPriceColumnBase);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.Order", deliveryAppServerModelsOrderTableBase);
            var deliveryAppServerModelsOrderMappingBase = new TableMappingBase<ColumnMappingBase>(order, deliveryAppServerModelsOrderTableBase, true);
            deliveryAppServerModelsOrderTableBase.AddTypeMapping(deliveryAppServerModelsOrderMappingBase, false);
            defaultTableMappings1.Add(deliveryAppServerModelsOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderIdColumnBase, order.FindProperty("OrderId")!, deliveryAppServerModelsOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, order.FindProperty("CreatedAt")!, deliveryAppServerModelsOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)customerIdColumnBase, order.FindProperty("CustomerId")!, deliveryAppServerModelsOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)driverIdColumnBase, order.FindProperty("DriverId")!, deliveryAppServerModelsOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)restaurantIdColumnBase0, order.FindProperty("RestaurantId")!, deliveryAppServerModelsOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)statusColumnBase, order.FindProperty("Status")!, deliveryAppServerModelsOrderMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)totalPriceColumnBase, order.FindProperty("TotalPrice")!, deliveryAppServerModelsOrderMappingBase);

            var tableMappings1 = new List<TableMapping>();
            order.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var ordersTable = new Table("Orders", null, relationalModel);
            var orderIdColumn = new Column("OrderId", "int", ordersTable);
            ordersTable.Columns.Add("OrderId", orderIdColumn);
            var createdAtColumn = new Column("CreatedAt", "datetime2", ordersTable);
            ordersTable.Columns.Add("CreatedAt", createdAtColumn);
            var customerIdColumn = new Column("CustomerId", "int", ordersTable);
            ordersTable.Columns.Add("CustomerId", customerIdColumn);
            var driverIdColumn = new Column("DriverId", "int", ordersTable)
            {
                IsNullable = true
            };
            ordersTable.Columns.Add("DriverId", driverIdColumn);
            var restaurantIdColumn0 = new Column("RestaurantId", "int", ordersTable);
            ordersTable.Columns.Add("RestaurantId", restaurantIdColumn0);
            var statusColumn = new Column("Status", "nvarchar(max)", ordersTable);
            ordersTable.Columns.Add("Status", statusColumn);
            var totalPriceColumn = new Column("TotalPrice", "decimal(18,2)", ordersTable);
            ordersTable.Columns.Add("TotalPrice", totalPriceColumn);
            var pK_Orders = new UniqueConstraint("PK_Orders", ordersTable, new[] { orderIdColumn });
            ordersTable.PrimaryKey = pK_Orders;
            var pK_OrdersUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.Order",
                new[] { "OrderId" });
            pK_Orders.MappedKeys.Add(pK_OrdersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_OrdersUc).Add(pK_Orders);
            ordersTable.UniqueConstraints.Add("PK_Orders", pK_Orders);
            var iX_Orders_CustomerId = new TableIndex(
            "IX_Orders_CustomerId", ordersTable, new[] { customerIdColumn }, false);
            var iX_Orders_CustomerIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.Order",
                new[] { "CustomerId" });
            iX_Orders_CustomerId.MappedIndexes.Add(iX_Orders_CustomerIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Orders_CustomerIdIx).Add(iX_Orders_CustomerId);
            ordersTable.Indexes.Add("IX_Orders_CustomerId", iX_Orders_CustomerId);
            var iX_Orders_DriverId = new TableIndex(
            "IX_Orders_DriverId", ordersTable, new[] { driverIdColumn }, false);
            var iX_Orders_DriverIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.Order",
                new[] { "DriverId" });
            iX_Orders_DriverId.MappedIndexes.Add(iX_Orders_DriverIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Orders_DriverIdIx).Add(iX_Orders_DriverId);
            ordersTable.Indexes.Add("IX_Orders_DriverId", iX_Orders_DriverId);
            var iX_Orders_RestaurantId = new TableIndex(
            "IX_Orders_RestaurantId", ordersTable, new[] { restaurantIdColumn0 }, false);
            var iX_Orders_RestaurantIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.Order",
                new[] { "RestaurantId" });
            iX_Orders_RestaurantId.MappedIndexes.Add(iX_Orders_RestaurantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Orders_RestaurantIdIx).Add(iX_Orders_RestaurantId);
            ordersTable.Indexes.Add("IX_Orders_RestaurantId", iX_Orders_RestaurantId);
            relationalModel.Tables.Add(("Orders", null), ordersTable);
            var ordersTableMapping = new TableMapping(order, ordersTable, true);
            ordersTable.AddTypeMapping(ordersTableMapping, false);
            tableMappings1.Add(ordersTableMapping);
            RelationalModel.CreateColumnMapping(orderIdColumn, order.FindProperty("OrderId")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, order.FindProperty("CreatedAt")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(customerIdColumn, order.FindProperty("CustomerId")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(driverIdColumn, order.FindProperty("DriverId")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(restaurantIdColumn0, order.FindProperty("RestaurantId")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(statusColumn, order.FindProperty("Status")!, ordersTableMapping);
            RelationalModel.CreateColumnMapping(totalPriceColumn, order.FindProperty("TotalPrice")!, ordersTableMapping);

            var orderItem = FindEntityType("deliveryApp.Server.Models.OrderItem")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            orderItem.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var deliveryAppServerModelsOrderItemTableBase = new TableBase("deliveryApp.Server.Models.OrderItem", null, relationalModel);
            var menuItemIdColumnBase0 = new ColumnBase<ColumnMappingBase>("MenuItemId", "int", deliveryAppServerModelsOrderItemTableBase);
            deliveryAppServerModelsOrderItemTableBase.Columns.Add("MenuItemId", menuItemIdColumnBase0);
            var orderIdColumnBase0 = new ColumnBase<ColumnMappingBase>("OrderId", "int", deliveryAppServerModelsOrderItemTableBase);
            deliveryAppServerModelsOrderItemTableBase.Columns.Add("OrderId", orderIdColumnBase0);
            var orderItemIdColumnBase = new ColumnBase<ColumnMappingBase>("OrderItemId", "int", deliveryAppServerModelsOrderItemTableBase);
            deliveryAppServerModelsOrderItemTableBase.Columns.Add("OrderItemId", orderItemIdColumnBase);
            var priceColumnBase0 = new ColumnBase<ColumnMappingBase>("Price", "decimal(18,2)", deliveryAppServerModelsOrderItemTableBase);
            deliveryAppServerModelsOrderItemTableBase.Columns.Add("Price", priceColumnBase0);
            var quantityColumnBase = new ColumnBase<ColumnMappingBase>("Quantity", "int", deliveryAppServerModelsOrderItemTableBase);
            deliveryAppServerModelsOrderItemTableBase.Columns.Add("Quantity", quantityColumnBase);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.OrderItem", deliveryAppServerModelsOrderItemTableBase);
            var deliveryAppServerModelsOrderItemMappingBase = new TableMappingBase<ColumnMappingBase>(orderItem, deliveryAppServerModelsOrderItemTableBase, true);
            deliveryAppServerModelsOrderItemTableBase.AddTypeMapping(deliveryAppServerModelsOrderItemMappingBase, false);
            defaultTableMappings2.Add(deliveryAppServerModelsOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderItemIdColumnBase, orderItem.FindProperty("OrderItemId")!, deliveryAppServerModelsOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)menuItemIdColumnBase0, orderItem.FindProperty("MenuItemId")!, deliveryAppServerModelsOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderIdColumnBase0, orderItem.FindProperty("OrderId")!, deliveryAppServerModelsOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)priceColumnBase0, orderItem.FindProperty("Price")!, deliveryAppServerModelsOrderItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)quantityColumnBase, orderItem.FindProperty("Quantity")!, deliveryAppServerModelsOrderItemMappingBase);

            var tableMappings2 = new List<TableMapping>();
            orderItem.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var orderItemsTable = new Table("OrderItems", null, relationalModel);
            var orderItemIdColumn = new Column("OrderItemId", "int", orderItemsTable);
            orderItemsTable.Columns.Add("OrderItemId", orderItemIdColumn);
            var menuItemIdColumn0 = new Column("MenuItemId", "int", orderItemsTable);
            orderItemsTable.Columns.Add("MenuItemId", menuItemIdColumn0);
            var orderIdColumn0 = new Column("OrderId", "int", orderItemsTable);
            orderItemsTable.Columns.Add("OrderId", orderIdColumn0);
            var priceColumn0 = new Column("Price", "decimal(18,2)", orderItemsTable);
            orderItemsTable.Columns.Add("Price", priceColumn0);
            var quantityColumn = new Column("Quantity", "int", orderItemsTable);
            orderItemsTable.Columns.Add("Quantity", quantityColumn);
            var pK_OrderItems = new UniqueConstraint("PK_OrderItems", orderItemsTable, new[] { orderItemIdColumn });
            orderItemsTable.PrimaryKey = pK_OrderItems;
            var pK_OrderItemsUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.OrderItem",
                new[] { "OrderItemId" });
            pK_OrderItems.MappedKeys.Add(pK_OrderItemsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_OrderItemsUc).Add(pK_OrderItems);
            orderItemsTable.UniqueConstraints.Add("PK_OrderItems", pK_OrderItems);
            var iX_OrderItems_MenuItemId = new TableIndex(
            "IX_OrderItems_MenuItemId", orderItemsTable, new[] { menuItemIdColumn0 }, false);
            var iX_OrderItems_MenuItemIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.OrderItem",
                new[] { "MenuItemId" });
            iX_OrderItems_MenuItemId.MappedIndexes.Add(iX_OrderItems_MenuItemIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_OrderItems_MenuItemIdIx).Add(iX_OrderItems_MenuItemId);
            orderItemsTable.Indexes.Add("IX_OrderItems_MenuItemId", iX_OrderItems_MenuItemId);
            var iX_OrderItems_OrderId = new TableIndex(
            "IX_OrderItems_OrderId", orderItemsTable, new[] { orderIdColumn0 }, false);
            var iX_OrderItems_OrderIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.OrderItem",
                new[] { "OrderId" });
            iX_OrderItems_OrderId.MappedIndexes.Add(iX_OrderItems_OrderIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_OrderItems_OrderIdIx).Add(iX_OrderItems_OrderId);
            orderItemsTable.Indexes.Add("IX_OrderItems_OrderId", iX_OrderItems_OrderId);
            relationalModel.Tables.Add(("OrderItems", null), orderItemsTable);
            var orderItemsTableMapping = new TableMapping(orderItem, orderItemsTable, true);
            orderItemsTable.AddTypeMapping(orderItemsTableMapping, false);
            tableMappings2.Add(orderItemsTableMapping);
            RelationalModel.CreateColumnMapping(orderItemIdColumn, orderItem.FindProperty("OrderItemId")!, orderItemsTableMapping);
            RelationalModel.CreateColumnMapping(menuItemIdColumn0, orderItem.FindProperty("MenuItemId")!, orderItemsTableMapping);
            RelationalModel.CreateColumnMapping(orderIdColumn0, orderItem.FindProperty("OrderId")!, orderItemsTableMapping);
            RelationalModel.CreateColumnMapping(priceColumn0, orderItem.FindProperty("Price")!, orderItemsTableMapping);
            RelationalModel.CreateColumnMapping(quantityColumn, orderItem.FindProperty("Quantity")!, orderItemsTableMapping);

            var restaurant = FindEntityType("deliveryApp.Server.Models.Restaurant")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            restaurant.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var deliveryAppServerModelsRestaurantTableBase = new TableBase("deliveryApp.Server.Models.Restaurant", null, relationalModel);
            var addressColumnBase = new ColumnBase<ColumnMappingBase>("Address", "nvarchar(max)", deliveryAppServerModelsRestaurantTableBase);
            deliveryAppServerModelsRestaurantTableBase.Columns.Add("Address", addressColumnBase);
            var cuisineTypeIdColumnBase0 = new ColumnBase<ColumnMappingBase>("CuisineTypeId", "int", deliveryAppServerModelsRestaurantTableBase);
            deliveryAppServerModelsRestaurantTableBase.Columns.Add("CuisineTypeId", cuisineTypeIdColumnBase0);
            var imageUrlColumnBase0 = new ColumnBase<ColumnMappingBase>("ImageUrl", "nvarchar(max)", deliveryAppServerModelsRestaurantTableBase);
            deliveryAppServerModelsRestaurantTableBase.Columns.Add("ImageUrl", imageUrlColumnBase0);
            var nameColumnBase1 = new ColumnBase<ColumnMappingBase>("Name", "nvarchar(max)", deliveryAppServerModelsRestaurantTableBase);
            deliveryAppServerModelsRestaurantTableBase.Columns.Add("Name", nameColumnBase1);
            var priceColumnBase1 = new ColumnBase<ColumnMappingBase>("Price", "decimal(18,2)", deliveryAppServerModelsRestaurantTableBase);
            deliveryAppServerModelsRestaurantTableBase.Columns.Add("Price", priceColumnBase1);
            var restaurantIdColumnBase1 = new ColumnBase<ColumnMappingBase>("RestaurantId", "int", deliveryAppServerModelsRestaurantTableBase);
            deliveryAppServerModelsRestaurantTableBase.Columns.Add("RestaurantId", restaurantIdColumnBase1);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.Restaurant", deliveryAppServerModelsRestaurantTableBase);
            var deliveryAppServerModelsRestaurantMappingBase = new TableMappingBase<ColumnMappingBase>(restaurant, deliveryAppServerModelsRestaurantTableBase, true);
            deliveryAppServerModelsRestaurantTableBase.AddTypeMapping(deliveryAppServerModelsRestaurantMappingBase, false);
            defaultTableMappings3.Add(deliveryAppServerModelsRestaurantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)restaurantIdColumnBase1, restaurant.FindProperty("RestaurantId")!, deliveryAppServerModelsRestaurantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)addressColumnBase, restaurant.FindProperty("Address")!, deliveryAppServerModelsRestaurantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cuisineTypeIdColumnBase0, restaurant.FindProperty("CuisineTypeId")!, deliveryAppServerModelsRestaurantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)imageUrlColumnBase0, restaurant.FindProperty("ImageUrl")!, deliveryAppServerModelsRestaurantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase1, restaurant.FindProperty("Name")!, deliveryAppServerModelsRestaurantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)priceColumnBase1, restaurant.FindProperty("Price")!, deliveryAppServerModelsRestaurantMappingBase);

            var tableMappings3 = new List<TableMapping>();
            restaurant.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var restaurantsTable = new Table("Restaurants", null, relationalModel);
            var restaurantIdColumn1 = new Column("RestaurantId", "int", restaurantsTable);
            restaurantsTable.Columns.Add("RestaurantId", restaurantIdColumn1);
            var addressColumn = new Column("Address", "nvarchar(max)", restaurantsTable);
            restaurantsTable.Columns.Add("Address", addressColumn);
            var cuisineTypeIdColumn0 = new Column("CuisineTypeId", "int", restaurantsTable);
            restaurantsTable.Columns.Add("CuisineTypeId", cuisineTypeIdColumn0);
            var imageUrlColumn0 = new Column("ImageUrl", "nvarchar(max)", restaurantsTable);
            restaurantsTable.Columns.Add("ImageUrl", imageUrlColumn0);
            var nameColumn1 = new Column("Name", "nvarchar(max)", restaurantsTable);
            restaurantsTable.Columns.Add("Name", nameColumn1);
            var priceColumn1 = new Column("Price", "decimal(18,2)", restaurantsTable);
            restaurantsTable.Columns.Add("Price", priceColumn1);
            var pK_Restaurants = new UniqueConstraint("PK_Restaurants", restaurantsTable, new[] { restaurantIdColumn1 });
            restaurantsTable.PrimaryKey = pK_Restaurants;
            var pK_RestaurantsUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.Restaurant",
                new[] { "RestaurantId" });
            pK_Restaurants.MappedKeys.Add(pK_RestaurantsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_RestaurantsUc).Add(pK_Restaurants);
            restaurantsTable.UniqueConstraints.Add("PK_Restaurants", pK_Restaurants);
            var iX_Restaurants_CuisineTypeId = new TableIndex(
            "IX_Restaurants_CuisineTypeId", restaurantsTable, new[] { cuisineTypeIdColumn0 }, false);
            var iX_Restaurants_CuisineTypeIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.Restaurant",
                new[] { "CuisineTypeId" });
            iX_Restaurants_CuisineTypeId.MappedIndexes.Add(iX_Restaurants_CuisineTypeIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Restaurants_CuisineTypeIdIx).Add(iX_Restaurants_CuisineTypeId);
            restaurantsTable.Indexes.Add("IX_Restaurants_CuisineTypeId", iX_Restaurants_CuisineTypeId);
            relationalModel.Tables.Add(("Restaurants", null), restaurantsTable);
            var restaurantsTableMapping = new TableMapping(restaurant, restaurantsTable, true);
            restaurantsTable.AddTypeMapping(restaurantsTableMapping, false);
            tableMappings3.Add(restaurantsTableMapping);
            RelationalModel.CreateColumnMapping(restaurantIdColumn1, restaurant.FindProperty("RestaurantId")!, restaurantsTableMapping);
            RelationalModel.CreateColumnMapping(addressColumn, restaurant.FindProperty("Address")!, restaurantsTableMapping);
            RelationalModel.CreateColumnMapping(cuisineTypeIdColumn0, restaurant.FindProperty("CuisineTypeId")!, restaurantsTableMapping);
            RelationalModel.CreateColumnMapping(imageUrlColumn0, restaurant.FindProperty("ImageUrl")!, restaurantsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn1, restaurant.FindProperty("Name")!, restaurantsTableMapping);
            RelationalModel.CreateColumnMapping(priceColumn1, restaurant.FindProperty("Price")!, restaurantsTableMapping);

            var restaurantHour = FindEntityType("deliveryApp.Server.Models.RestaurantHour")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            restaurantHour.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var deliveryAppServerModelsRestaurantHourTableBase = new TableBase("deliveryApp.Server.Models.RestaurantHour", null, relationalModel);
            var closeTimeColumnBase = new ColumnBase<ColumnMappingBase>("CloseTime", "time", deliveryAppServerModelsRestaurantHourTableBase);
            deliveryAppServerModelsRestaurantHourTableBase.Columns.Add("CloseTime", closeTimeColumnBase);
            var dayOfWeekColumnBase = new ColumnBase<ColumnMappingBase>("DayOfWeek", "int", deliveryAppServerModelsRestaurantHourTableBase);
            deliveryAppServerModelsRestaurantHourTableBase.Columns.Add("DayOfWeek", dayOfWeekColumnBase);
            var openTimeColumnBase = new ColumnBase<ColumnMappingBase>("OpenTime", "time", deliveryAppServerModelsRestaurantHourTableBase);
            deliveryAppServerModelsRestaurantHourTableBase.Columns.Add("OpenTime", openTimeColumnBase);
            var restaurantHourIdColumnBase = new ColumnBase<ColumnMappingBase>("RestaurantHourId", "int", deliveryAppServerModelsRestaurantHourTableBase);
            deliveryAppServerModelsRestaurantHourTableBase.Columns.Add("RestaurantHourId", restaurantHourIdColumnBase);
            var restaurantIdColumnBase2 = new ColumnBase<ColumnMappingBase>("RestaurantId", "int", deliveryAppServerModelsRestaurantHourTableBase);
            deliveryAppServerModelsRestaurantHourTableBase.Columns.Add("RestaurantId", restaurantIdColumnBase2);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.RestaurantHour", deliveryAppServerModelsRestaurantHourTableBase);
            var deliveryAppServerModelsRestaurantHourMappingBase = new TableMappingBase<ColumnMappingBase>(restaurantHour, deliveryAppServerModelsRestaurantHourTableBase, true);
            deliveryAppServerModelsRestaurantHourTableBase.AddTypeMapping(deliveryAppServerModelsRestaurantHourMappingBase, false);
            defaultTableMappings4.Add(deliveryAppServerModelsRestaurantHourMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)restaurantHourIdColumnBase, restaurantHour.FindProperty("RestaurantHourId")!, deliveryAppServerModelsRestaurantHourMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)closeTimeColumnBase, restaurantHour.FindProperty("CloseTime")!, deliveryAppServerModelsRestaurantHourMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dayOfWeekColumnBase, restaurantHour.FindProperty("DayOfWeek")!, deliveryAppServerModelsRestaurantHourMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)openTimeColumnBase, restaurantHour.FindProperty("OpenTime")!, deliveryAppServerModelsRestaurantHourMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)restaurantIdColumnBase2, restaurantHour.FindProperty("RestaurantId")!, deliveryAppServerModelsRestaurantHourMappingBase);

            var tableMappings4 = new List<TableMapping>();
            restaurantHour.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var restaurantHoursTable = new Table("RestaurantHours", null, relationalModel);
            var restaurantHourIdColumn = new Column("RestaurantHourId", "int", restaurantHoursTable);
            restaurantHoursTable.Columns.Add("RestaurantHourId", restaurantHourIdColumn);
            var closeTimeColumn = new Column("CloseTime", "time", restaurantHoursTable);
            restaurantHoursTable.Columns.Add("CloseTime", closeTimeColumn);
            var dayOfWeekColumn = new Column("DayOfWeek", "int", restaurantHoursTable);
            restaurantHoursTable.Columns.Add("DayOfWeek", dayOfWeekColumn);
            var openTimeColumn = new Column("OpenTime", "time", restaurantHoursTable);
            restaurantHoursTable.Columns.Add("OpenTime", openTimeColumn);
            var restaurantIdColumn2 = new Column("RestaurantId", "int", restaurantHoursTable);
            restaurantHoursTable.Columns.Add("RestaurantId", restaurantIdColumn2);
            var pK_RestaurantHours = new UniqueConstraint("PK_RestaurantHours", restaurantHoursTable, new[] { restaurantHourIdColumn });
            restaurantHoursTable.PrimaryKey = pK_RestaurantHours;
            var pK_RestaurantHoursUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.RestaurantHour",
                new[] { "RestaurantHourId" });
            pK_RestaurantHours.MappedKeys.Add(pK_RestaurantHoursUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_RestaurantHoursUc).Add(pK_RestaurantHours);
            restaurantHoursTable.UniqueConstraints.Add("PK_RestaurantHours", pK_RestaurantHours);
            var iX_RestaurantHours_RestaurantId = new TableIndex(
            "IX_RestaurantHours_RestaurantId", restaurantHoursTable, new[] { restaurantIdColumn2 }, false);
            var iX_RestaurantHours_RestaurantIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.RestaurantHour",
                new[] { "RestaurantId" });
            iX_RestaurantHours_RestaurantId.MappedIndexes.Add(iX_RestaurantHours_RestaurantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_RestaurantHours_RestaurantIdIx).Add(iX_RestaurantHours_RestaurantId);
            restaurantHoursTable.Indexes.Add("IX_RestaurantHours_RestaurantId", iX_RestaurantHours_RestaurantId);
            relationalModel.Tables.Add(("RestaurantHours", null), restaurantHoursTable);
            var restaurantHoursTableMapping = new TableMapping(restaurantHour, restaurantHoursTable, true);
            restaurantHoursTable.AddTypeMapping(restaurantHoursTableMapping, false);
            tableMappings4.Add(restaurantHoursTableMapping);
            RelationalModel.CreateColumnMapping(restaurantHourIdColumn, restaurantHour.FindProperty("RestaurantHourId")!, restaurantHoursTableMapping);
            RelationalModel.CreateColumnMapping(closeTimeColumn, restaurantHour.FindProperty("CloseTime")!, restaurantHoursTableMapping);
            RelationalModel.CreateColumnMapping(dayOfWeekColumn, restaurantHour.FindProperty("DayOfWeek")!, restaurantHoursTableMapping);
            RelationalModel.CreateColumnMapping(openTimeColumn, restaurantHour.FindProperty("OpenTime")!, restaurantHoursTableMapping);
            RelationalModel.CreateColumnMapping(restaurantIdColumn2, restaurantHour.FindProperty("RestaurantId")!, restaurantHoursTableMapping);

            var role = FindEntityType("deliveryApp.Server.Models.Role")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            role.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var deliveryAppServerModelsRoleTableBase = new TableBase("deliveryApp.Server.Models.Role", null, relationalModel);
            var roleIdColumnBase = new ColumnBase<ColumnMappingBase>("RoleId", "int", deliveryAppServerModelsRoleTableBase);
            deliveryAppServerModelsRoleTableBase.Columns.Add("RoleId", roleIdColumnBase);
            var roleNameColumnBase = new ColumnBase<ColumnMappingBase>("RoleName", "nvarchar(max)", deliveryAppServerModelsRoleTableBase);
            deliveryAppServerModelsRoleTableBase.Columns.Add("RoleName", roleNameColumnBase);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.Role", deliveryAppServerModelsRoleTableBase);
            var deliveryAppServerModelsRoleMappingBase = new TableMappingBase<ColumnMappingBase>(role, deliveryAppServerModelsRoleTableBase, true);
            deliveryAppServerModelsRoleTableBase.AddTypeMapping(deliveryAppServerModelsRoleMappingBase, false);
            defaultTableMappings5.Add(deliveryAppServerModelsRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)roleIdColumnBase, role.FindProperty("RoleId")!, deliveryAppServerModelsRoleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)roleNameColumnBase, role.FindProperty("RoleName")!, deliveryAppServerModelsRoleMappingBase);

            var tableMappings5 = new List<TableMapping>();
            role.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var rolesTable = new Table("Roles", null, relationalModel);
            var roleIdColumn = new Column("RoleId", "int", rolesTable);
            rolesTable.Columns.Add("RoleId", roleIdColumn);
            var roleNameColumn = new Column("RoleName", "nvarchar(max)", rolesTable);
            rolesTable.Columns.Add("RoleName", roleNameColumn);
            var pK_Roles = new UniqueConstraint("PK_Roles", rolesTable, new[] { roleIdColumn });
            rolesTable.PrimaryKey = pK_Roles;
            var pK_RolesUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.Role",
                new[] { "RoleId" });
            pK_Roles.MappedKeys.Add(pK_RolesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_RolesUc).Add(pK_Roles);
            rolesTable.UniqueConstraints.Add("PK_Roles", pK_Roles);
            relationalModel.Tables.Add(("Roles", null), rolesTable);
            var rolesTableMapping = new TableMapping(role, rolesTable, true);
            rolesTable.AddTypeMapping(rolesTableMapping, false);
            tableMappings5.Add(rolesTableMapping);
            RelationalModel.CreateColumnMapping(roleIdColumn, role.FindProperty("RoleId")!, rolesTableMapping);
            RelationalModel.CreateColumnMapping(roleNameColumn, role.FindProperty("RoleName")!, rolesTableMapping);

            var user = FindEntityType("deliveryApp.Server.Models.User")!;

            var defaultTableMappings6 = new List<TableMappingBase<ColumnMappingBase>>();
            user.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings6);
            var deliveryAppServerModelsUserTableBase = new TableBase("deliveryApp.Server.Models.User", null, relationalModel);
            var emailColumnBase = new ColumnBase<ColumnMappingBase>("Email", "nvarchar(max)", deliveryAppServerModelsUserTableBase);
            deliveryAppServerModelsUserTableBase.Columns.Add("Email", emailColumnBase);
            var passwordColumnBase = new ColumnBase<ColumnMappingBase>("Password", "nvarchar(max)", deliveryAppServerModelsUserTableBase);
            deliveryAppServerModelsUserTableBase.Columns.Add("Password", passwordColumnBase);
            var roleIdColumnBase0 = new ColumnBase<ColumnMappingBase>("RoleId", "int", deliveryAppServerModelsUserTableBase);
            deliveryAppServerModelsUserTableBase.Columns.Add("RoleId", roleIdColumnBase0);
            var userIdColumnBase = new ColumnBase<ColumnMappingBase>("UserId", "int", deliveryAppServerModelsUserTableBase);
            deliveryAppServerModelsUserTableBase.Columns.Add("UserId", userIdColumnBase);
            relationalModel.DefaultTables.Add("deliveryApp.Server.Models.User", deliveryAppServerModelsUserTableBase);
            var deliveryAppServerModelsUserMappingBase = new TableMappingBase<ColumnMappingBase>(user, deliveryAppServerModelsUserTableBase, true);
            deliveryAppServerModelsUserTableBase.AddTypeMapping(deliveryAppServerModelsUserMappingBase, false);
            defaultTableMappings6.Add(deliveryAppServerModelsUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userIdColumnBase, user.FindProperty("UserId")!, deliveryAppServerModelsUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase, user.FindProperty("Email")!, deliveryAppServerModelsUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)passwordColumnBase, user.FindProperty("Password")!, deliveryAppServerModelsUserMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)roleIdColumnBase0, user.FindProperty("RoleId")!, deliveryAppServerModelsUserMappingBase);

            var tableMappings6 = new List<TableMapping>();
            user.SetRuntimeAnnotation("Relational:TableMappings", tableMappings6);
            var usersTable = new Table("Users", null, relationalModel);
            var userIdColumn = new Column("UserId", "int", usersTable);
            usersTable.Columns.Add("UserId", userIdColumn);
            var emailColumn = new Column("Email", "nvarchar(max)", usersTable);
            usersTable.Columns.Add("Email", emailColumn);
            var passwordColumn = new Column("Password", "nvarchar(max)", usersTable);
            usersTable.Columns.Add("Password", passwordColumn);
            var roleIdColumn0 = new Column("RoleId", "int", usersTable);
            usersTable.Columns.Add("RoleId", roleIdColumn0);
            var pK_Users = new UniqueConstraint("PK_Users", usersTable, new[] { userIdColumn });
            usersTable.PrimaryKey = pK_Users;
            var pK_UsersUc = RelationalModel.GetKey(this,
                "deliveryApp.Server.Models.User",
                new[] { "UserId" });
            pK_Users.MappedKeys.Add(pK_UsersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UsersUc).Add(pK_Users);
            usersTable.UniqueConstraints.Add("PK_Users", pK_Users);
            var iX_Users_RoleId = new TableIndex(
            "IX_Users_RoleId", usersTable, new[] { roleIdColumn0 }, false);
            var iX_Users_RoleIdIx = RelationalModel.GetIndex(this,
                "deliveryApp.Server.Models.User",
                new[] { "RoleId" });
            iX_Users_RoleId.MappedIndexes.Add(iX_Users_RoleIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Users_RoleIdIx).Add(iX_Users_RoleId);
            usersTable.Indexes.Add("IX_Users_RoleId", iX_Users_RoleId);
            relationalModel.Tables.Add(("Users", null), usersTable);
            var usersTableMapping = new TableMapping(user, usersTable, true);
            usersTable.AddTypeMapping(usersTableMapping, false);
            tableMappings6.Add(usersTableMapping);
            RelationalModel.CreateColumnMapping(userIdColumn, user.FindProperty("UserId")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(emailColumn, user.FindProperty("Email")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(passwordColumn, user.FindProperty("Password")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(roleIdColumn0, user.FindProperty("RoleId")!, usersTableMapping);
            var fK_MenuItems_Restaurants_RestaurantId = new ForeignKeyConstraint(
                "FK_MenuItems_Restaurants_RestaurantId", menuItemsTable, restaurantsTable,
                new[] { restaurantIdColumn },
                restaurantsTable.FindUniqueConstraint("PK_Restaurants")!, ReferentialAction.Cascade);
            var fK_MenuItems_Restaurants_RestaurantIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.MenuItem",
                new[] { "RestaurantId" },
                "deliveryApp.Server.Models.Restaurant",
                new[] { "RestaurantId" });
            fK_MenuItems_Restaurants_RestaurantId.MappedForeignKeys.Add(fK_MenuItems_Restaurants_RestaurantIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_MenuItems_Restaurants_RestaurantIdFk).Add(fK_MenuItems_Restaurants_RestaurantId);
            menuItemsTable.ForeignKeyConstraints.Add(fK_MenuItems_Restaurants_RestaurantId);
            restaurantsTable.ReferencingForeignKeyConstraints.Add(fK_MenuItems_Restaurants_RestaurantId);
            var fK_OrderItems_MenuItems_MenuItemId = new ForeignKeyConstraint(
                "FK_OrderItems_MenuItems_MenuItemId", orderItemsTable, menuItemsTable,
                new[] { menuItemIdColumn0 },
                menuItemsTable.FindUniqueConstraint("PK_MenuItems")!, ReferentialAction.Cascade);
            var fK_OrderItems_MenuItems_MenuItemIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.OrderItem",
                new[] { "MenuItemId" },
                "deliveryApp.Server.Models.MenuItem",
                new[] { "MenuItemId" });
            fK_OrderItems_MenuItems_MenuItemId.MappedForeignKeys.Add(fK_OrderItems_MenuItems_MenuItemIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_OrderItems_MenuItems_MenuItemIdFk).Add(fK_OrderItems_MenuItems_MenuItemId);
            orderItemsTable.ForeignKeyConstraints.Add(fK_OrderItems_MenuItems_MenuItemId);
            menuItemsTable.ReferencingForeignKeyConstraints.Add(fK_OrderItems_MenuItems_MenuItemId);
            var fK_OrderItems_Orders_OrderId = new ForeignKeyConstraint(
                "FK_OrderItems_Orders_OrderId", orderItemsTable, ordersTable,
                new[] { orderIdColumn0 },
                ordersTable.FindUniqueConstraint("PK_Orders")!, ReferentialAction.Cascade);
            var fK_OrderItems_Orders_OrderIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.OrderItem",
                new[] { "OrderId" },
                "deliveryApp.Server.Models.Order",
                new[] { "OrderId" });
            fK_OrderItems_Orders_OrderId.MappedForeignKeys.Add(fK_OrderItems_Orders_OrderIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_OrderItems_Orders_OrderIdFk).Add(fK_OrderItems_Orders_OrderId);
            orderItemsTable.ForeignKeyConstraints.Add(fK_OrderItems_Orders_OrderId);
            ordersTable.ReferencingForeignKeyConstraints.Add(fK_OrderItems_Orders_OrderId);
            var fK_Orders_Restaurants_RestaurantId = new ForeignKeyConstraint(
                "FK_Orders_Restaurants_RestaurantId", ordersTable, restaurantsTable,
                new[] { restaurantIdColumn0 },
                restaurantsTable.FindUniqueConstraint("PK_Restaurants")!, ReferentialAction.Restrict);
            var fK_Orders_Restaurants_RestaurantIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.Order",
                new[] { "RestaurantId" },
                "deliveryApp.Server.Models.Restaurant",
                new[] { "RestaurantId" });
            fK_Orders_Restaurants_RestaurantId.MappedForeignKeys.Add(fK_Orders_Restaurants_RestaurantIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Orders_Restaurants_RestaurantIdFk).Add(fK_Orders_Restaurants_RestaurantId);
            ordersTable.ForeignKeyConstraints.Add(fK_Orders_Restaurants_RestaurantId);
            restaurantsTable.ReferencingForeignKeyConstraints.Add(fK_Orders_Restaurants_RestaurantId);
            var fK_Orders_Users_CustomerId = new ForeignKeyConstraint(
                "FK_Orders_Users_CustomerId", ordersTable, usersTable,
                new[] { customerIdColumn },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Restrict);
            var fK_Orders_Users_CustomerIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.Order",
                new[] { "CustomerId" },
                "deliveryApp.Server.Models.User",
                new[] { "UserId" });
            fK_Orders_Users_CustomerId.MappedForeignKeys.Add(fK_Orders_Users_CustomerIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Orders_Users_CustomerIdFk).Add(fK_Orders_Users_CustomerId);
            ordersTable.ForeignKeyConstraints.Add(fK_Orders_Users_CustomerId);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_Orders_Users_CustomerId);
            var fK_Orders_Users_DriverId = new ForeignKeyConstraint(
                "FK_Orders_Users_DriverId", ordersTable, usersTable,
                new[] { driverIdColumn },
                usersTable.FindUniqueConstraint("PK_Users")!, ReferentialAction.Restrict);
            var fK_Orders_Users_DriverIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.Order",
                new[] { "DriverId" },
                "deliveryApp.Server.Models.User",
                new[] { "UserId" });
            fK_Orders_Users_DriverId.MappedForeignKeys.Add(fK_Orders_Users_DriverIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Orders_Users_DriverIdFk).Add(fK_Orders_Users_DriverId);
            ordersTable.ForeignKeyConstraints.Add(fK_Orders_Users_DriverId);
            usersTable.ReferencingForeignKeyConstraints.Add(fK_Orders_Users_DriverId);
            var fK_Restaurants_CuisineTypes_CuisineTypeId = new ForeignKeyConstraint(
                "FK_Restaurants_CuisineTypes_CuisineTypeId", restaurantsTable, cuisineTypesTable,
                new[] { cuisineTypeIdColumn0 },
                cuisineTypesTable.FindUniqueConstraint("PK_CuisineTypes")!, ReferentialAction.Restrict);
            var fK_Restaurants_CuisineTypes_CuisineTypeIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.Restaurant",
                new[] { "CuisineTypeId" },
                "deliveryApp.Server.Models.CuisineType",
                new[] { "CuisineTypeId" });
            fK_Restaurants_CuisineTypes_CuisineTypeId.MappedForeignKeys.Add(fK_Restaurants_CuisineTypes_CuisineTypeIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Restaurants_CuisineTypes_CuisineTypeIdFk).Add(fK_Restaurants_CuisineTypes_CuisineTypeId);
            restaurantsTable.ForeignKeyConstraints.Add(fK_Restaurants_CuisineTypes_CuisineTypeId);
            cuisineTypesTable.ReferencingForeignKeyConstraints.Add(fK_Restaurants_CuisineTypes_CuisineTypeId);
            var fK_RestaurantHours_Restaurants_RestaurantId = new ForeignKeyConstraint(
                "FK_RestaurantHours_Restaurants_RestaurantId", restaurantHoursTable, restaurantsTable,
                new[] { restaurantIdColumn2 },
                restaurantsTable.FindUniqueConstraint("PK_Restaurants")!, ReferentialAction.Restrict);
            var fK_RestaurantHours_Restaurants_RestaurantIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.RestaurantHour",
                new[] { "RestaurantId" },
                "deliveryApp.Server.Models.Restaurant",
                new[] { "RestaurantId" });
            fK_RestaurantHours_Restaurants_RestaurantId.MappedForeignKeys.Add(fK_RestaurantHours_Restaurants_RestaurantIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_RestaurantHours_Restaurants_RestaurantIdFk).Add(fK_RestaurantHours_Restaurants_RestaurantId);
            restaurantHoursTable.ForeignKeyConstraints.Add(fK_RestaurantHours_Restaurants_RestaurantId);
            restaurantsTable.ReferencingForeignKeyConstraints.Add(fK_RestaurantHours_Restaurants_RestaurantId);
            var fK_Users_Roles_RoleId = new ForeignKeyConstraint(
                "FK_Users_Roles_RoleId", usersTable, rolesTable,
                new[] { roleIdColumn0 },
                rolesTable.FindUniqueConstraint("PK_Roles")!, ReferentialAction.Restrict);
            var fK_Users_Roles_RoleIdFk = RelationalModel.GetForeignKey(this,
                "deliveryApp.Server.Models.User",
                new[] { "RoleId" },
                "deliveryApp.Server.Models.Role",
                new[] { "RoleId" });
            fK_Users_Roles_RoleId.MappedForeignKeys.Add(fK_Users_Roles_RoleIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Users_Roles_RoleIdFk).Add(fK_Users_Roles_RoleId);
            usersTable.ForeignKeyConstraints.Add(fK_Users_Roles_RoleId);
            rolesTable.ReferencingForeignKeyConstraints.Add(fK_Users_Roles_RoleId);
            return relationalModel.MakeReadOnly();
        }
    }
}
